//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalles_Venta = new HashSet<Detalles_Venta>();
        }
    
        public int ID_Producto { get; set; }
        public string Nombre { get; set; }
        public int Precio { get; set; }
        public string Categoria { get; set; }
        public string Tallas_disponibles { get; set; }
        public string Color { get; set; }
        public int Stock { get; set; }
        public int ID_Proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Venta> Detalles_Venta { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
